const knowledgeBase = {
    web_app: {
        structure: ["public", "src/components", "src/pages", "src/styles", "src/hooks", "src/services", "src/utils", "src/assets"],
        libraries: ["react", "react-dom", "react-router-dom", "axios", "tailwindcss"],
        starterCode: {
            "src/App.jsx": "import React from 'react';\nimport { BrowserRouter, Routes, Route } from 'react-router-dom';\nimport Home from './pages/Home';\nimport Products from './pages/Products';\nimport Cart from './pages/Cart';\nimport './styles/App.css';\n\nfunction App() {\n  return (\n    <BrowserRouter>\n      <div className='app'>\n        <nav className='navbar'>\n          <h1>متجري</h1>\n          <ul>\n            <li><a href='/'>الرئيسية</a></li>\n            <li><a href='/products'>المنتجات</a></li>\n            <li><a href='/cart'>السلة</a></li>\n          </ul>\n        </nav>\n        <main className='main-content'>\n          <Routes>\n            <Route path='/' element={<Home />} />\n            <Route path='/products' element={<Products />} />\n            <Route path='/cart' element={<Cart />} />\n          </Routes>\n        </main>\n        <footer className='footer'>\n          <p>© 2024 متجري. جميع الحقوق محفوظة.</p>\n        </footer>\n      </div>\n    </BrowserRouter>\n  );\n}\n\nexport default App;\n",
            "src/pages/Home.jsx": "import React from 'react';\n\nfunction Home() {\n  const featuredProducts = [\n    { id: 1, name: 'هاتف ذكي', price: '١٢٠٠ ريال', image: '📱', description: 'هاتف ذكي بشاشة عالية الدقة' },\n    { id: 2, name: 'حاسوب محمول', price: '٣٥٠٠ ريال', image: '💻', description: 'حاسوب محمول قوي للأعمال' },\n    { id: 3, name: 'ساعة ذكية', price: '٨٠٠ ريال', image: '⌚', description: 'ساعة ذكية بمميزات متعددة' },\n    { id: 4, name: 'سماعات', price: '٤٠٠ ريال', image: '🎧', description: 'سماعات عالية الجودة' },\n    { id: 5, name: 'تابلت', price: '١٥٠٠ ريال', image: '📋', description: 'تابلت للدراسة والعمل' },\n    { id: 6, name: 'كاميرا', price: '٢٠٠٠ ريال', image: '📷', description: 'كاميرا احترافية' },\n  ];\n\n  return (\n    <div className='home'>\n      <section className='hero'>\n        <h2>مرحباً بك في متجرنا</h2>\n        <p>أفضل المنتجات بأفضل الأسعار</p>\n      </section>\n      <section className='featured'>\n        <h2>منتجات مميزة</h2>\n        <div className='products-grid'>\n          {featuredProducts.map(product => (\n            <div key={product.id} className='product-card'>\n              <span className='product-icon'>{product.image}</span>\n              <h3>{product.name}</h3>\n              <p>{product.description}</p>\n              <p className='price'>{product.price}</p>\n              <button className='btn-add-to-cart'>أضف إلى السلة</button>\n            </div>\n          ))}\n        </div>\n      </section>\n    </div>\n  );\n}\n\nexport default Home;\n",
            "src/pages/Products.jsx": "import React, { useState } from 'react';\n\nfunction Products() {\n  const [products] = useState([\n    { id: 1, name: 'هاتف ذكي', price: '١٢٠٠ ريال', category: 'إلكترونيات', image: '📱', stock: 10 },\n    { id: 2, name: 'حاسوب محمول', price: '٣٥٠٠ ريال', category: 'إلكترونيات', image: '💻', stock: 5 },\n    { id: 3, name: 'ساعة ذكية', price: '٨٠٠ ريال', category: 'إلكترونيات', image: '⌚', stock: 15 },\n    { id: 4, name: 'سماعات', price: '٤٠٠ ريال', category: 'إلكترونيات', image: '🎧', stock: 20 },\n    { id: 5, name: 'تابلت', price: '١٥٠٠ ريال', category: 'إلكترونيات', image: '📋', stock: 8 },\n    { id: 6, name: 'كاميرا', price: '٢٠٠٠ ريال', category: 'إلكترونيات', image: '📷', stock: 3 },\n    { id: 7, name: 'طابعة', price: '٦٠٠ ريال', category: 'مكتب', image: '🖨️', stock: 12 },\n    { id: 8, name: 'مكتب', price: '٩٠٠ ريال', category: 'أثاث', image: '🪑', stock: 4 },\n  ]);\n  const [search, setSearch] = useState('');\n\n  const filtered = products.filter(p => p.name.includes(search) || p.category.includes(search));\n\n  return (\n    <div className='products-page'>\n      <h2>جميع المنتجات</h2>\n      <input type='text' placeholder='ابحث عن منتج...' value={search} onChange={e => setSearch(e.target.value)} className='search-input' />\n      <div className='products-grid'>\n        {filtered.map(product => (\n          <div key={product.id} className='product-card'>\n            <span className='product-icon'>{product.image}</span>\n            <h3>{product.name}</h3>\n            <p className='category'>{product.category}</p>\n            <p className='price'>{product.price}</p>\n            <p className='stock'>المخزون: {product.stock}</p>\n            <button className='btn-add-to-cart'>أضف إلى السلة</button>\n          </div>\n        ))}\n      </div>\n    </div>\n  );\n}\n\nexport default Products;\n",
            "src/pages/Cart.jsx": "import React, { useState } from 'react';\n\nfunction Cart() {\n  const [cartItems, setCartItems] = useState([\n    { id: 1, name: 'هاتف ذكي', price: '١٢٠٠ ريال', quantity: 1, image: '📱' },\n    { id: 2, name: 'سماعات', price: '٤٠٠ ريال', quantity: 2, image: '🎧' },\n  ]);\n\n  const total = cartItems.reduce((sum, item) => sum + (parseInt(item.price) * item.quantity), 0);\n\n  return (\n    <div className='cart-page'>\n      <h2>سلة المشتريات</h2>\n      {cartItems.length === 0 ? (\n        <p className='empty-cart'>السلة فارغة</p>\n      ) : (\n        <>\n          <div className='cart-items'>\n            {cartItems.map(item => (\n              <div key={item.id} className='cart-item'>\n                <span className='product-icon'>{item.image}</span>\n                <div className='item-details'>\n                  <h3>{item.name}</h3>\n                  <p>{item.price}</p>\n                  <p>الكمية: {item.quantity}</p>\n                </div>\n              </div>\n            ))}\n          </div>\n          <div className='cart-summary'>\n            <h3>المجموع: {total} ريال</h3>\n            <button className='btn-checkout'>إتمام الشراء</button>\n          </div>\n        </>\n      )}\n    </div>\n  );\n}\n\nexport default Cart;\n",
            "src/styles/App.css": "body { margin: 0; font-family: 'Cairo', sans-serif; direction: rtl; background: #f5f5f5; }\n.app { min-height: 100vh; display: flex; flex-direction: column; }\n.navbar { background: #2c3e50; color: white; padding: 1rem 2rem; display: flex; justify-content: space-between; align-items: center; }\n.navbar h1 { margin: 0; font-size: 1.5rem; }\n.navbar ul { list-style: none; display: flex; gap: 1rem; margin: 0; padding: 0; }\n.navbar a { color: white; text-decoration: none; padding: 0.5rem 1rem; border-radius: 4px; }\n.navbar a:hover { background: #34495e; }\n.main-content { flex: 1; padding: 2rem; max-width: 1200px; margin: 0 auto; width: 100%; }\n.hero { text-align: center; padding: 3rem 1rem; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 12px; margin-bottom: 2rem; }\n.hero h2 { font-size: 2rem; margin-bottom: 0.5rem; }\n.products-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 1.5rem; margin-top: 1rem; }\n.product-card { background: white; border-radius: 12px; padding: 1.5rem; text-align: center; box-shadow: 0 2px 8px rgba(0,0,0,0.1); transition: transform 0.2s; }\n.product-card:hover { transform: translateY(-4px); box-shadow: 0 4px 16px rgba(0,0,0,0.15); }\n.product-icon { font-size: 3rem; display: block; margin-bottom: 0.5rem; }\n.product-card h3 { margin: 0.5rem 0; color: #2c3e50; }\n.price { color: #e74c3c; font-weight: bold; font-size: 1.2rem; }\n.btn-add-to-cart, .btn-checkout { background: #27ae60; color: white; border: none; padding: 0.75rem 1.5rem; border-radius: 8px; cursor: pointer; font-size: 1rem; margin-top: 0.5rem; transition: background 0.2s; }\n.btn-add-to-cart:hover, .btn-checkout:hover { background: #219a52; }\n.search-input { width: 100%; padding: 0.75rem; border: 1px solid #ddd; border-radius: 8px; font-size: 1rem; margin-bottom: 1rem; }\n.cart-item { display: flex; align-items: center; gap: 1rem; background: white; padding: 1rem; border-radius: 8px; margin-bottom: 0.5rem; }\n.cart-summary { text-align: left; margin-top: 1rem; padding: 1rem; background: white; border-radius: 8px; }\n.footer { background: #2c3e50; color: white; text-align: center; padding: 1rem; margin-top: auto; }\n.category { color: #7f8c8d; font-size: 0.9rem; }\n.stock { color: #2980b9; font-size: 0.85rem; }\n.empty-cart { text-align: center; color: #7f8c8d; padding: 2rem; }\n@media (max-width: 768px) {\n  .products-grid { grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); }\n  .navbar { flex-direction: column; gap: 0.5rem; }\n  .hero h2 { font-size: 1.5rem; }\n}"
        }
    },
    api: {
        structure: ["src/routes", "src/controllers", "src/models", "src/middleware", "src/services", "src/utils", "src/config"],
        libraries: ["express", "cors", "dotenv", "mongoose", "jsonwebtoken", "bcryptjs"],
        starterCode: {
            "src/server.js": "const express = require('express');\nconst cors = require('cors');\nconst dotenv = require('dotenv');\n\ndotenv.config();\n\nconst app = express();\nconst PORT = process.env.PORT || 5000;\n\napp.use(cors());\napp.use(express.json());\n\napp.get('/api/health', (req, res) => {\n  res.json({ status: 'healthy', timestamp: new Date().toISOString() });\n});\n\napp.get('/api/products', (req, res) => {\n  const products = [\n    { id: 1, name: 'منتج 1', price: 100, description: 'وصف المنتج 1' },\n    { id: 2, name: 'منتج 2', price: 200, description: 'وصف المنتج 2' },\n    { id: 3, name: 'منتج 3', price: 300, description: 'وصف المنتج 3' },\n  ];\n  res.json({ status: 'success', data: products });\n});\n\napp.post('/api/orders', (req, res) => {\n  const { productId, quantity } = req.body;\n  res.json({ status: 'success', message: 'تم إنشاء الطلب', order: { id: Date.now(), productId, quantity } });\n});\n\napp.listen(PORT, () => {\n  console.log(`Server running on port ${PORT}`);\n});\n",
            "src/routes/products.js": "const express = require('express');\nconst router = express.Router();\n\nconst products = [\n  { id: 1, name: 'هاتف ذكي', price: 1200, category: 'إلكترونيات', stock: 10 },\n  { id: 2, name: 'حاسوب محمول', price: 3500, category: 'إلكترونيات', stock: 5 },\n  { id: 3, name: 'ساعة ذكية', price: 800, category: 'إلكترونيات', stock: 15 },\n  { id: 4, name: 'سماعات', price: 400, category: 'إلكترونيات', stock: 20 },\n  { id: 5, name: 'تابلت', price: 1500, category: 'إلكترونيات', stock: 8 },\n  { id: 6, name: 'كاميرا', price: 2000, category: 'إلكترونيات', stock: 3 },\n  { id: 7, name: 'طابعة', price: 600, category: 'مكتب', stock: 12 },\n  { id: 8, name: 'مكتب', price: 900, category: 'أثاث', stock: 4 },\n];\n\nrouter.get('/', (req, res) => {\n  const { category } = req.query;\n  let filtered = products;\n  if (category) {\n    filtered = products.filter(p => p.category === category);\n  }\n  res.json({ status: 'success', count: filtered.length, data: filtered });\n});\n\nrouter.get('/:id', (req, res) => {\n  const product = products.find(p => p.id === parseInt(req.params.id));\n  if (!product) return res.status(404).json({ status: 'error', message: 'المنتج غير موجود' });\n  res.json({ status: 'success', data: product });\n});\n\nmodule.exports = router;\n",
            "src/routes/orders.js": "const express = require('express');\nconst router = express.Router();\n\nlet orders = [];\n\nrouter.post('/', (req, res) => {\n  const { productId, quantity, customerName, customerEmail } = req.body;\n  \n  if (!productId || !quantity) {\n    return res.status(400).json({ status: 'error', message: 'معرف المنتج والكمية مطلوبان' });\n  }\n\n  const order = {\n    id: orders.length + 1,\n    productId,\n    quantity,\n    customerName: customerName || 'عميل',\n    customerEmail: customerEmail || 'customer@example.com',\n    status: 'pending',\n    createdAt: new Date().toISOString()\n  };\n\n  orders.push(order);\n  res.status(201).json({ status: 'success', data: order });\n});\n\nrouter.get('/', (req, res) => {\n  res.json({ status: 'success', count: orders.length, data: orders });\n});\n\nrouter.get('/:id', (req, res) => {\n  const order = orders.find(o => o.id === parseInt(req.params.id));\n  if (!order) return res.status(404).json({ status: 'error', message: 'الطلب غير موجود' });\n  res.json({ status: 'success', data: order });\n});\n\nrouter.patch('/:id/status', (req, res) => {\n  const order = orders.find(o => o.id === parseInt(req.params.id));\n  if (!order) return res.status(404).json({ status: 'error', message: 'الطلب غير موجود' });\n  order.status = req.body.status || order.status;\n  res.json({ status: 'success', data: order });\n});\n\nmodule.exports = router;\n"
        }
    },
    script: {
        structure: ["src", "tests"],
        libraries: ["fs", "path", "axios", "dotenv"],
        starterCode: {
            "src/index.js": "// المشروع جاهز للعمل\nconsole.log('🚀 تم إنشاء المشروع بنجاح!');\nconsole.log('📁 هيكل المشروع جاهز للتطوير.');\n\nconst main = async () => {\n  console.log('✅ كل شيء يعمل بشكل صحيح.');\n  console.log('📝 يمكنك البدء في كتابة الكود الخاص بك هنا.');\n};\n\nmain().catch(console.error);\n",
            "src/utils.js": "const fs = require('fs');\nconst path = require('path');\n\nfunction ensureDir(dirPath) {\n  if (!fs.existsSync(dirPath)) {\n    fs.mkdirSync(dirPath, { recursive: true });\n  }\n  return dirPath;\n}\n\nfunction readJSON(filePath) {\n  try {\n    return JSON.parse(fs.readFileSync(filePath, 'utf8'));\n  } catch {\n    return null;\n  }\n}\n\nfunction writeJSON(filePath, data) {\n  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');\n}\n\nmodule.exports = { ensureDir, readJSON, writeJSON };\n",
            "tests/test.js": "const assert = require('assert');\n\nconsole.log('🧪 بدء الاختبارات...');\n\n// اختبار بسيط\nconst result = 1 + 1;\nassert.strictEqual(result, 2, '1 + 1 يجب أن يساوي 2');\n\nconsole.log('✅ جميع الاختبارات ناجحة!');\n"
        }
    }
};

function research(goal, keywords) {
    if (!goal || typeof goal !== 'string') goal = '';
    
    const lowerGoal = goal.toLowerCase();
    let projectType = "script"; // افتراضي = script بدلاً من unknown
    
    // كشف نوع المشروع - دعم عربي وإنجليزي
    if (
        lowerGoal.includes("web") || lowerGoal.includes("app") || lowerGoal.includes("react") ||
        lowerGoal.includes("next") || lowerGoal.includes("vue") || lowerGoal.includes("frontend") ||
        lowerGoal.includes("موقع") || lowerGoal.includes("ويب") || lowerGoal.includes("واجهة") ||
        lowerGoal.includes("تطبيق ويب") || lowerGoal.includes("متجر") || lowerGoal.includes("تجارة") ||
        lowerGoal.includes("الكتروني") || lowerGoal.includes("إلكتروني") || lowerGoal.includes("صفحات") ||
        lowerGoal.includes("منتجات") || lowerGoal.includes("سلة") || lowerGoal.includes("شراء") ||
        lowerGoal.includes("ecommerce") || lowerGoal.includes("e-commerce") || lowerGoal.includes("shop") ||
        lowerGoal.includes("store") || lowerGoal.includes("commerce")
    ) {
        projectType = "web_app";
    } else if (
        lowerGoal.includes("api") || lowerGoal.includes("server") || lowerGoal.includes("backend") ||
        lowerGoal.includes("express") || lowerGoal.includes("fastify") || lowerGoal.includes("endpoint") ||
        lowerGoal.includes("خادم") || lowerGoal.includes("خلفية") || lowerGoal.includes("راوت") ||
        lowerGoal.includes("route") || lowerGoal.includes("router") || lowerGoal.includes("controller")
    ) {
        projectType = "api";
    } else if (
        lowerGoal.includes("script") || lowerGoal.includes("tool") || lowerGoal.includes("cli") ||
        lowerGoal.includes("سكريبت") || lowerGoal.includes("أداة") || lowerGoal.includes("ملف") ||
        lowerGoal.includes("file") || lowerGoal.includes("create") || lowerGoal.includes("أنشئ") ||
        lowerGoal.includes("ابن") || lowerGoal.includes("build") || lowerGoal.includes("txt") ||
        lowerGoal.includes("hello") || lowerGoal.includes("print")
    ) {
        projectType = "script";
    }
    
    const recommendation = knowledgeBase[projectType] || knowledgeBase["script"];
    
    return {
        projectType,
        recommendedStructure: recommendation.structure,
        recommendedLibraries: recommendation.libraries,
        starterCode: recommendation.starterCode || {}
    };
}

module.exports = { research, knowledgeBase };
